#!/bin/bash

# install kylin on the Ambari server instance
if [[ "$SERF_TAG_AMBARI_SERVER" == "true" ]] ;then
  echo run kylin deploy script
  nohup /usr/local/kylin/deploy.sh > /var/log/kylin-deploy.log
fi
